### ISSUE TITLE
QQWry.dat应该放到哪个位置？

### ISSUE THREAD

**Issue by helloxz** [gai871013/ip-location#1]
演示代码中没看到加载`QQWry.dat`，纯真数据库应该放到哪个目录啊？

**Comment by gai871013** [comment]
> 演示代码中没看到加载`QQWry.dat`，纯真数据库应该放到哪个目录啊？

如果是自己有修改 `QQWry.dat` 文件的需求可以放到项目的任意目录，实例化的时候把路径作为参数传进去就可以了，否则的话不需要指定 `QQWry.dat` 。项目中已经包含最新的QQwry.dat文件

```
<?php
use Gai871013\IpLocation\IpLocation;

$path_to_file = '/path-to-file.dat';
$ipLocation = new IpLocation($path_to_file);
```

**Comment by gai871013** [comment]
项目中已经包含最新的QQwry.dat文件
